/*
    Created by - Aniruddha Pandit,Bhavesh Chaudhauri
*/
package gymrat;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author root
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
/*  20 */     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("biceps.jpg")));
/*  21 */     this.loginpnl.setVisible(true);
/*  22 */     this.forgotpnl.setVisible(false);
/*  23 */     this.chngpwdpnl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginpnl = new javax.swing.JPanel();
        namelbl = new javax.swing.JLabel();
        pwdlbl = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        resetbtn = new javax.swing.JButton();
        loginbtn = new javax.swing.JButton();
        pwdtf = new javax.swing.JPasswordField();
        registerlbl = new javax.swing.JLabel();
        forgotpwdlbl = new javax.swing.JLabel();
        loginicon = new javax.swing.JLabel();
        forgotpnl = new javax.swing.JPanel();
        rquslbl = new javax.swing.JLabel();
        anstf = new javax.swing.JTextField();
        forgotbackbtn = new javax.swing.JButton();
        changebtn = new javax.swing.JButton();
        recoveryquslbl = new javax.swing.JLabel();
        anslbl = new javax.swing.JLabel();
        forgoticonlbl = new javax.swing.JLabel();
        chngpwdpnl = new javax.swing.JPanel();
        cnfpwdtf = new javax.swing.JTextField();
        newpswdtf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cnfbtn = new javax.swing.JButton();
        chngbackbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newmnuitem = new javax.swing.JMenuItem();
        adminitm = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        aboutmenuitem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gymrat[Login]");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namelbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        namelbl.setForeground(new java.awt.Color(153, 153, 153));
        namelbl.setText("Name :");
        loginpnl.add(namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, -1));

        pwdlbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pwdlbl.setForeground(new java.awt.Color(153, 153, 153));
        pwdlbl.setText("Password :");
        loginpnl.add(pwdlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        nametf.setBackground(new java.awt.Color(153, 153, 153));
        nametf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nametf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loginpnl.add(nametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 160, -1));

        resetbtn.setBackground(new java.awt.Color(153, 153, 153));
        resetbtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        resetbtn.setForeground(new java.awt.Color(0, 0, 0));
        resetbtn.setText("Reset");
        resetbtn.setBorderPainted(false);
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });
        loginpnl.add(resetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        loginbtn.setBackground(new java.awt.Color(153, 153, 153));
        loginbtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(0, 0, 0));
        loginbtn.setText("Login");
        loginbtn.setBorderPainted(false);
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        loginpnl.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        pwdtf.setBackground(new java.awt.Color(153, 153, 153));
        pwdtf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pwdtf.setForeground(new java.awt.Color(0, 0, 0));
        pwdtf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loginpnl.add(pwdtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 160, 24));

        registerlbl.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        registerlbl.setForeground(new java.awt.Color(153, 153, 153));
        registerlbl.setText("Register");
        registerlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerlblMouseClicked(evt);
            }
        });
        loginpnl.add(registerlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        forgotpwdlbl.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        forgotpwdlbl.setForeground(new java.awt.Color(153, 153, 153));
        forgotpwdlbl.setText("Forgot Password?");
        forgotpwdlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpwdlblMouseClicked(evt);
            }
        });
        loginpnl.add(forgotpwdlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 130, -1));

        loginicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymrat/login.jpg"))); // NOI18N
        loginpnl.add(loginicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(loginpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        forgotpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rquslbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rquslbl.setForeground(new java.awt.Color(153, 153, 153));
        rquslbl.setText("jLabel1");
        forgotpnl.add(rquslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 320, -1));

        anstf.setBackground(new java.awt.Color(153, 153, 153));
        anstf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        anstf.setForeground(new java.awt.Color(0, 0, 0));
        anstf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        forgotpnl.add(anstf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 280, -1));

        forgotbackbtn.setBackground(new java.awt.Color(153, 153, 153));
        forgotbackbtn.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        forgotbackbtn.setForeground(new java.awt.Color(0, 0, 0));
        forgotbackbtn.setText("Back");
        forgotbackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotbackbtnActionPerformed(evt);
            }
        });
        forgotpnl.add(forgotbackbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 80, -1));

        changebtn.setBackground(new java.awt.Color(153, 153, 153));
        changebtn.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        changebtn.setForeground(new java.awt.Color(0, 0, 0));
        changebtn.setText("Change");
        changebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebtnActionPerformed(evt);
            }
        });
        forgotpnl.add(changebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        recoveryquslbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        recoveryquslbl.setForeground(new java.awt.Color(153, 153, 153));
        recoveryquslbl.setText("Recover Question :");
        forgotpnl.add(recoveryquslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        anslbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        anslbl.setForeground(new java.awt.Color(153, 153, 153));
        anslbl.setText("Answer :");
        forgotpnl.add(anslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 202, 90, 30));

        forgoticonlbl.setText("jLabel1");
        forgotpnl.add(forgoticonlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        getContentPane().add(forgotpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        chngpwdpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cnfpwdtf.setBackground(new java.awt.Color(153, 153, 153));
        cnfpwdtf.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cnfpwdtf.setForeground(new java.awt.Color(0, 0, 0));
        cnfpwdtf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        chngpwdpnl.add(cnfpwdtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 198, 258, -1));

        newpswdtf.setBackground(new java.awt.Color(153, 153, 153));
        newpswdtf.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        newpswdtf.setForeground(new java.awt.Color(0, 0, 0));
        newpswdtf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        chngpwdpnl.add(newpswdtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 139, 258, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("New Password :");
        chngpwdpnl.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 142, 117, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Confirm Password :");
        chngpwdpnl.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 201, 139, -1));

        cnfbtn.setBackground(new java.awt.Color(153, 153, 153));
        cnfbtn.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        cnfbtn.setForeground(new java.awt.Color(0, 0, 0));
        cnfbtn.setText("Confirm");
        cnfbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnfbtnActionPerformed(evt);
            }
        });
        chngpwdpnl.add(cnfbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 299, -1, -1));

        chngbackbtn.setBackground(new java.awt.Color(153, 153, 153));
        chngbackbtn.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        chngbackbtn.setForeground(new java.awt.Color(0, 0, 0));
        chngbackbtn.setText("Back");
        chngbackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chngbackbtnActionPerformed(evt);
            }
        });
        chngpwdpnl.add(chngbackbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 299, -1, -1));
        chngpwdpnl.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        getContentPane().add(chngpwdpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        jMenu1.setText("File");

        newmnuitem.setText("New");
        newmnuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newmnuitemActionPerformed(evt);
            }
        });
        jMenu1.add(newmnuitem);

        adminitm.setText("Admin");
        adminitm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminitmActionPerformed(evt);
            }
        });
        jMenu1.add(adminitm);

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        aboutmenuitem.setText("About");
        aboutmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutmenuitemActionPerformed(evt);
            }
        });
        jMenu2.add(aboutmenuitem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        this.nametf.setText("");this.pwdtf.setText("");
    }//GEN-LAST:event_resetbtnActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        try {
/* 382 */       String name = this.nametf.getText();
/* 383 */       String password = this.pwdtf.getText();
/* 384 */       if (name.isBlank() || password.isBlank()) {
/*     */         
/* 386 */         JOptionPane.showMessageDialog(this, "Please fill both the fields");
/*     */       } else {
/* 388 */         Class.forName("org.postgresql.Driver");
/*     */ 
/*     */         
/* 391 */         try { Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/project", "postgres", "Turbotime");
/* 392 */           Statement stmt = con.createStatement();
/* 393 */           ResultSet rs = stmt.executeQuery("select * from customer where name='" + name + "'and password='" + password + "'");
/* 394 */           if (rs.next()) {
/*     */             
/* 396 */             name = this.nametf.getText();
/* 397 */             new main(name).setVisible(true);
/* 398 */             dispose();
/*     */           
/*     */           }
/*     */           else {
/*     */             
/* 403 */             JOptionPane.showMessageDialog(this, "Incorrect Name or Password");
/*     */           }  }
/* 405 */         catch (SQLException ex)
/* 406 */         { System.out.println(ex); } 
/*     */       } 
/* 408 */     } catch (ClassNotFoundException ex) {
/* 409 */       System.out.println(ex);
/*     */     }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void registerlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerlblMouseClicked
        new register().setVisible(true);
    }//GEN-LAST:event_registerlblMouseClicked

    private void forgotpwdlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpwdlblMouseClicked
        String name = this.nametf.getText();
/* 436 */     if (name.isBlank()) {
/*     */       
/* 438 */       JOptionPane.showMessageDialog(this, "Please Enter Name");
/*     */     } else {
/*     */ 
/*     */       
/*     */       try {
/*     */ 
/*     */         
/* 445 */         Class.forName("org.postgresql.Driver");
/* 446 */         Connection c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/project", "postgres", "Turbotime");
/* 447 */         Statement stmt = c.createStatement();
/* 448 */         ResultSet rs = stmt.executeQuery("select recovery_qus,recovery_ans from customer where name='" + name + "'");
/* 449 */         if (!rs.next()) {
/*     */           
/* 451 */           JOptionPane.showMessageDialog(this, "User doesn't exist");
/*     */         
/*     */         }
/*     */         else {
/*     */           
/* 456 */           this.rquslbl.setText(rs.getString(1));
/* 457 */           this.forgotpnl.setVisible(true);
/* 458 */           this.loginpnl.setVisible(false);
/* 459 */           this.anstf.setText("");
/*     */         } 
/* 461 */       } catch (Exception e) {
/*     */         
/* 463 */         System.out.println(e);
/*     */       } 
/*     */     }
    }//GEN-LAST:event_forgotpwdlblMouseClicked

    private void forgotbackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotbackbtnActionPerformed
        this.loginpnl.setVisible(true);
/* 552 */     this.chngpwdpnl.setVisible(false);
/* 553 */     this.forgotpnl.setVisible(false);
    }//GEN-LAST:event_forgotbackbtnActionPerformed

    private void changebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebtnActionPerformed
        String ans = this.anstf.getText();
/* 474 */     String name = this.nametf.getText();
/*     */ 
/*     */ 
/*     */ 
/*     */     
/*     */     try {
/* 480 */       Class.forName("org.postgresql.Driver");
/* 481 */       Connection c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/project", "postgres", "Turbotime");
/* 482 */       Statement stmt = c.createStatement();
/* 483 */       ResultSet rs = stmt.executeQuery("select recovery_qus,recovery_ans from customer where name='" + name + "'");
/* 484 */       if (rs.next())
/*     */       {
/* 486 */         if (ans.equalsIgnoreCase(rs.getString(2))) {
/*     */           
/* 488 */           this.loginpnl.setVisible(false);
/* 489 */           this.chngpwdpnl.setVisible(true);
/* 490 */           this.forgotpnl.setVisible(false);
/*     */         
/*     */         }
/*     */         else {
/*     */           
/* 495 */           JOptionPane.showMessageDialog(this, "Incorrect Answer");
/*     */         } 
/*     */       }
/* 498 */     } catch (ClassNotFoundException|SQLException e) {
/*     */       
/* 500 */       System.out.print(e);
/*     */     }
    }//GEN-LAST:event_changebtnActionPerformed

    private void cnfbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnfbtnActionPerformed
        String password = this.newpswdtf.getText();
/* 510 */     String name = this.nametf.getText();
/* 511 */     String cnfpassword = this.cnfpwdtf.getText();
/* 512 */     if (password.isBlank() && cnfpassword.isBlank()) {
/*     */       
/* 514 */       JOptionPane.showMessageDialog(this, "Please enter both passwords");
/*     */     }
/* 516 */     else if (password.equals(new String(this.cnfpwdtf.getText()))) {
/*     */ 
/*     */       
/*     */       try {
/*     */         
/* 521 */         Class.forName("org.postgresql.Driver");
/* 522 */         Connection c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/project", "postgres", "Turbotime");
/* 523 */         Statement stmt = c.createStatement();
/* 524 */         int rs = stmt.executeUpdate("update customer set password='" + password + "' where name='" + name + "'");
/* 525 */         if (rs == 1)
/*     */         {
/* 527 */           JOptionPane.showMessageDialog(this, "Password changed Successsfully");
/*     */           
/* 529 */           this.loginpnl.setVisible(true);
/* 530 */           this.chngpwdpnl.setVisible(false);
/* 531 */           this.forgotpnl.setVisible(false);
/*     */         }
/*     */         else
/*     */         {
/* 535 */           JOptionPane.showMessageDialog(this, "Password cannot be changed !!");
/*     */         }
/*     */       
/* 538 */       } catch (Exception e) {
/*     */         
/* 540 */         System.out.print(e);
/*     */       }
/*     */     
/*     */     } else {
/*     */       
/* 545 */       JOptionPane.showMessageDialog(this, "Password Doesn't Match");
/*     */     }
    }//GEN-LAST:event_cnfbtnActionPerformed

    private void chngbackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chngbackbtnActionPerformed
/* 529 */           this.loginpnl.setVisible(false);
/* 530 */           this.chngpwdpnl.setVisible(false);
/* 531 */           this.forgotpnl.setVisible(true);
    }//GEN-LAST:event_chngbackbtnActionPerformed

    private void adminitmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminitmActionPerformed
        new admin().setVisible(true);
    }//GEN-LAST:event_adminitmActionPerformed

    private void newmnuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newmnuitemActionPerformed
        new register().setVisible(true);
    }//GEN-LAST:event_newmnuitemActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
    
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void aboutmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutmenuitemActionPerformed
    new about().setVisible(true);
    }//GEN-LAST:event_aboutmenuitemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutmenuitem;
    private javax.swing.JMenuItem adminitm;
    private javax.swing.JLabel anslbl;
    private javax.swing.JTextField anstf;
    private javax.swing.JButton changebtn;
    private javax.swing.JButton chngbackbtn;
    private javax.swing.JPanel chngpwdpnl;
    private javax.swing.JButton cnfbtn;
    private javax.swing.JTextField cnfpwdtf;
    private javax.swing.JButton forgotbackbtn;
    private javax.swing.JLabel forgoticonlbl;
    private javax.swing.JPanel forgotpnl;
    private javax.swing.JLabel forgotpwdlbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel loginicon;
    private javax.swing.JPanel loginpnl;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametf;
    private javax.swing.JMenuItem newmnuitem;
    private javax.swing.JTextField newpswdtf;
    private javax.swing.JLabel pwdlbl;
    private javax.swing.JPasswordField pwdtf;
    private javax.swing.JLabel recoveryquslbl;
    private javax.swing.JLabel registerlbl;
    private javax.swing.JButton resetbtn;
    private javax.swing.JLabel rquslbl;
    // End of variables declaration//GEN-END:variables
}
